#pragma kernel FractalNoise

#include "Includes/Noise.hlsl"
#include "Includes/ComputeUtils.hlsl"

struct NoiseLayer
{
    float3 offset;
    int    octaves;
    float  amplitude;
    float  frequency;
    float  lacunarity;
    float  persistence;
};

RWStructuredBuffer<float>    noise;
StructuredBuffer<NoiseLayer> noiseLayers;

float3 chunkOffset;
float3 center;
float radius;
int resolution;
int spacing;
int numLayers;

float Noise(float3 worldPos);

[numthreads(8,8,8)]
void FractalNoise (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= resolution || id.y >= resolution || id.z >= resolution) return;
    
    float3 worldPos = id.xyz * spacing + chunkOffset - center;
    float value = Noise(worldPos);
    noise[Index(id.xyz, resolution)] = value;
}

float Noise(float3 worldPos)
{
    float dist = radius - length(worldPos);
    if (dist > radius * 0.2) return 0.0;
    
    float3 noisePos = worldPos / radius;
    float value = 0;
    
    for (int n = 0; n < numLayers; n++)
    {
        NoiseLayer nl = noiseLayers[n];
        float3 offset = nl.offset;
        float freq = nl.frequency;
        float amp = nl.amplitude;
        for (int i = 0; i < nl.octaves; i++)
        {
            value += snoise(noisePos * freq + offset) * amp;
            freq *= nl.lacunarity;
            amp *= nl.persistence;
        }
    }
    
    return value * 0.1 * radius;
}